
export enum EquipmentStatus {
  ACTIVE = 'Ativo',
  INACTIVE = 'Inativo',
  MAINTENANCE = 'Em Manutenção',
  DISCARDED = 'Descartado'
}

export interface Equipment {
  id: string;
  tag: string;
  name: string;
  manufacturer: string;
  model: string;
  serialNumber: string;
  range: string; // Faixa de medição
  resolution: string; // Resolução
  accuracy: string; // Exatidão/Classe/Tolerância Aceitável
  location: string;
  supplier?: string; // Fornecedor / Laboratório Externo
  status: EquipmentStatus;
  lastCalibrationDate?: string;
  nextCalibrationDate: string;
  createdAt: string;
  // Specific fields for Safety Valves
  openingPressure?: string;
  closingPressure?: string;
  // Configuração padrão de grupos de teste (Ex: ["Tração", "Compressão"])
  defaultTestGroups?: string[];
}

export interface MeasurementPoint {
  id: string;
  referenceValue: number; // Valor Padrão
  measuredValue: number; // Valor Lido (Instrumento)
  error: number; // measured - reference
  uncertainty?: number; // Incerteza expandida
  isOutlier?: boolean;
}

export interface MeasurementGroup {
  id: string;
  name: string; // Ex: "Tração", "Compressão", "Sentido Horário"
  measurements: MeasurementPoint[];
}

export interface CalibrationRecord {
  id: string;
  equipmentId: string;
  date: string;
  technician: string;
  temperature: number;
  humidity: number;
  standardUsed: string; // Padrão utilizado
  measurements: MeasurementPoint[]; // Mantido para compatibilidade (Legacy)
  measurementGroups?: MeasurementGroup[]; // Novo campo para múltiplos testes
  result: 'Aprovado' | 'Reprovado' | 'Aprovado com Restrições';
  notes: string;
  aiAnalysis?: string; // Analysis generated by Gemini
}

export interface BudgetEquipmentLink {
  id: string;
  tag: string;
  name: string;
}

export interface BudgetRecord {
  id: string;
  // Alterado para suportar múltiplos equipamentos
  equipments: BudgetEquipmentLink[]; 
  provider: string; // Laboratório ou Fornecedor
  date: string;
  type: 'Calibração' | 'Manutenção' | 'Reparo' | 'Peças';
  cost: number;
  status: 'Pendente' | 'Aprovado' | 'Concluído' | 'Cancelado';
  notes?: string;
}

// Navigation types
export type ViewState = 
  | { type: 'DASHBOARD' }
  | { type: 'EQUIPMENT_DETAILS'; equipmentId: string }
  | { type: 'NEW_CALIBRATION'; equipmentId: string }
  | { type: 'EDIT_CALIBRATION'; equipmentId: string; calibrationId: string }
  | { type: 'VIEW_REPORT'; calibrationId: string }
  | { type: 'BUDGETS' };
